"""Tests for preprocess_cif and mean_pool in extract_cif_embeddings.py.

extract_cif_embeddings.py imports from CrystaLLM at module level, so we stub
that package before importing the script module.
"""
import importlib
import importlib.util
import os
import sys
import types
import unittest.mock as mock

import pytest
import torch


# ── Stub CrystaLLM so the module can be imported without the real package ─────

def _stub_crystallm():
    stub = types.ModuleType("crystallm")
    stub.CIFTokenizer = mock.MagicMock()
    stub.GPTConfig = mock.MagicMock()
    stub.GPT = mock.MagicMock()
    sys.modules.setdefault("crystallm", stub)


_stub_crystallm()

SCRIPT = os.path.join(os.path.dirname(__file__), "..", "scripts", "extract_cif_embeddings.py")


@pytest.fixture(scope="module")
def ece():
    spec = importlib.util.spec_from_file_location("extract_cif_embeddings", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# ── preprocess_cif ────────────────────────────────────────────────────────────

def test_strips_comment_lines(ece):
    cif = "# This is a comment\ndata_block\n_cell_length_a 5.0\n"
    result = ece.preprocess_cif(cif)
    assert "# This is a comment" not in result
    assert "data_block" in result


def test_strips_blank_lines(ece):
    cif = "data_block\n\n\n_cell 5.0\n"
    result = ece.preprocess_cif(cif)
    lines = [l for l in result.split("\n") if l.strip()]
    # no interior blank lines (trailing newline added by function is ok)
    assert all(l.strip() for l in lines)


def test_strips_pymatgen_lines(ece):
    cif = "data_block\n# generated by pymatgen\n_cell 5.0\n"
    result = ece.preprocess_cif(cif)
    assert "pymatgen" not in result


def test_preserves_content_lines(ece):
    cif = "_cell_length_a 5.4321\n_cell_length_b 3.1234\n"
    result = ece.preprocess_cif(cif)
    assert "_cell_length_a 5.4321" in result
    assert "_cell_length_b 3.1234" in result


def test_always_ends_with_newline(ece):
    cif = "_cell 5.0"
    result = ece.preprocess_cif(cif)
    assert result.endswith("\n")


def test_empty_cif(ece):
    result = ece.preprocess_cif("")
    # only the trailing newline sentinel remains
    assert result.strip() == ""


# ── mean_pool ─────────────────────────────────────────────────────────────────

def test_mean_pool_exact_average(ece):
    # batch=1, T=3 tokens, D=2; all tokens valid
    hidden = torch.tensor([[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]])  # (1,3,2)
    lengths = torch.tensor([3])
    pooled = ece.mean_pool(hidden, lengths)
    assert pooled.shape == (1, 2)
    assert torch.allclose(pooled, torch.tensor([[3.0, 4.0]]))


def test_mean_pool_ignores_padding(ece):
    # T=4 but only first 2 tokens are real; last 2 are padding (zeros)
    hidden = torch.tensor([[[1.0, 0.0], [3.0, 0.0], [0.0, 0.0], [0.0, 0.0]]])
    lengths = torch.tensor([2])
    pooled = ece.mean_pool(hidden, lengths)
    assert torch.allclose(pooled, torch.tensor([[2.0, 0.0]]))


def test_mean_pool_batch_of_two(ece):
    # batch=2 with different lengths
    hidden = torch.zeros(2, 4, 3)
    hidden[0, 0] = torch.tensor([1.0, 1.0, 1.0])
    hidden[0, 1] = torch.tensor([3.0, 3.0, 3.0])
    # tokens 2,3 are padding for item 0
    hidden[1, 0] = torch.tensor([2.0, 2.0, 2.0])
    hidden[1, 1] = torch.tensor([4.0, 4.0, 4.0])
    hidden[1, 2] = torch.tensor([6.0, 6.0, 6.0])
    # tokens 3 is padding for item 1
    lengths = torch.tensor([2, 3])
    pooled = ece.mean_pool(hidden, lengths)
    assert pooled.shape == (2, 3)
    assert torch.allclose(pooled[0], torch.tensor([2.0, 2.0, 2.0]))
    assert torch.allclose(pooled[1], torch.tensor([4.0, 4.0, 4.0]))


def test_mean_pool_single_token(ece):
    hidden = torch.tensor([[[7.0, 8.0, 9.0]]])  # length=1
    lengths = torch.tensor([1])
    pooled = ece.mean_pool(hidden, lengths)
    assert torch.allclose(pooled, torch.tensor([[7.0, 8.0, 9.0]]))
